### PR TITLE
Update base image and use latest pygments

### PR DESCRIPTION
**Pull request by dario23**

### CODE REVIEW

**Comment by dario23** [comment]
draft PR, i want to wait until https://github.com/pygments/pygments/pull/1813 is merged and then update the pygments URL with the latest pygments master after that (instead of linking to the fork currently).

**Review by vakaras — APPROVED** [review]
LGTM

**Comment by vakaras** [comment]
My experience is that it can take a really long time for a PR to be merged into the pygments mainstream. Therefore, I would suggest merging this PR now and creating a new one once the pygments PR lands.

**Comment by dario23** [comment]
there's been some communication back and forth from the original pygments PR author and a maintainer in the last two days, i'd be willing to wait another 1-2 days in the hopes it gets merged soon.

**Comment by vakaras** [comment]
Sounds reasonable ☺

**Review by vakaras — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
